version: '3.6'
services:
  server:
    image: sherrylv:latesst
    build: .
    container_name: sherrylv1
  proxy:
    image: nginx
    container_name: sherrylv2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080